version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 81:80
    volumes:
    - ./src:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./my_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
